-- Kea Type System Formalization
-- Lean 4 formalization of Kea's Remy-style row polymorphism and HM inference.
-- See FORMAL.md at the repo root for the Rust ↔ Lean mapping.

import Kea.Ty
import Kea.Substitution
import Kea.FreeVars
import Kea.OccursCheck
import Kea.LacksConstraints
import Kea.Unify
import Kea.Generalize
import Kea.Dimensions
import Kea.Traits
import Kea.Typing
import Kea.Eval
import Kea.DataFrame
import Kea.Properties.SubstIdempotent
import Kea.Properties.UnifyReflexive
import Kea.Properties.UnifyConsistent
import Kea.Properties.OccursCheckSound
import Kea.Properties.RowFieldsSorted
import Kea.Properties.RemyPreservesLabels
import Kea.Properties.LacksBlocksDuplicate
import Kea.Properties.RecordRoundTrip
import Kea.Properties.RecordStructuralProjection
import Kea.Properties.TraitCoherence
import Kea.Properties.DataFrameMutateDropRoundTrip
import Kea.Properties.DataFrameMutateExistingErrors
import Kea.Properties.TraitBoundsPreserved
import Kea.Properties.DataFrameVerbPreservation
import Kea.Properties.DecomposeFields
import Kea.Properties.ColumnBoundary
import Kea.Properties.UnifyExtends
import Kea.Properties.SubstCompose
import Kea.Properties.SubstBridge
import Kea.Properties.TemporalLeafParity
import Kea.Properties.PrecisionLeafParity
import Kea.Properties.DecimalParity
import Kea.Properties.ShapeConstructorParity
import Kea.Properties.HigherOrderConstructorParity
import Kea.Properties.ExistentialParity
import Kea.Properties.ForallParity
import Kea.Properties.NominalAdtParity
import Kea.Properties.NominalAdtTypingBridge
import Kea.Properties.RuntimeWrapperParity
import Kea.Properties.BoundaryAssignability
import Kea.Properties.DynamicBoundaryTypingBridge
import Kea.Properties.WrapperBoundaryTypingBridge
import Kea.Properties.GroupedTaggedParity
import Kea.Properties.GroupedTaggedTypingBridge
import Kea.Properties.BoundaryAscriptionSyntax
import Kea.Properties.BoundarySurfaceSuite
import Kea.ColExpr
